#!/bin/bash

function get_abs_path() {
    readlink -f $1 
}

SELF_PATH=$(dirname $(get_abs_path $(which $0)))

cd ~/bin
ln -fs $SELF_PATH/apktools/apktool
ln -fs $SELF_PATH/smali/baksmali
ln -fs $SELF_PATH/smali/smali
ln -fs $SELF_PATH/jadx/jadx-0.7.1/bin/jadx
ln -fs $SELF_PATH/jadx/jadx-0.7.1/bin/jadx-gui

case $(uname -s) in
    Linux)
        ln -fs $SELF_PATH/dextra/dextra.ELF64 dextra
        ;;
    Darwin)
        ln -fs $SELF_PATH/dextra/dextra dextra
        ;;
esac